<a href="https://colab.research.google.com/github/kabir993/kabiropedia/blob/main/one_hot_encoding_practical.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
dataset= pd.read_csv("/content/train_u6lujuX_CVtuZ9i (1).csv")

In [ ]:
dataset.head(5)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [ ]:
dataset.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [ ]:
dataset['Gender'].fillna(dataset['Gender'].mode()[0], inplace=True)

In [ ]:
dataset.isnull().sum()

Loan_ID               0
Gender                0
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [ ]:
dataset['Married'].fillna(dataset['Married'].mode()[0], inplace=True)

In [ ]:
dataset.isnull().sum()

Loan_ID               0
Gender                0
Married               0
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [ ]:
en_data=dataset[['Gender','Married']]

In [ ]:
en_data

     Gender Married
0      Male      No
1      Male     Yes
2      Male     Yes
3      Male     Yes
4      Male      No
..      ...     ...
609  Female      No
610    Male     Yes
611    Male     Yes
612    Male     Yes
613  Female      No

[614 rows x 2 columns]

In [ ]:
pd.get_dummies(en_data)

     Gender_Female  Gender_Male  Married_No  Married_Yes
0            False         True        True        False
1            False         True       False         True
2            False         True       False         True
3            False         True       False         True
4            False         True        True        False
..             ...          ...         ...          ...
609           True        False        True        False
610          False         True       False         True
611          False         True       False         True
612          False         True       False         True
613           True        False        True        False

[614 rows x 4 columns]

In [ ]:
pd.get_dummies(en_data).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Gender_Female  614 non-null    bool
 1   Gender_Male    614 non-null    bool
 2   Married_No     614 non-null    bool
 3   Married_Yes    614 non-null    bool
dtypes: bool(4)
memory usage: 2.5 KB

In [ ]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (1.5.2)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (3.5.0)

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
Ohe=OneHotEncoder() # Define the OneHotEncoder object as Ohe
Ohe.fit_transform(en_data) # Use Ohe (capital 'O') to call the fit_transform method, maintaining consistency.

<614x4 sparse matrix of type '<class 'numpy.float64'>'
	with 1228 stored elements in Compressed Sparse Row format>

In [ ]:
ar=Ohe.fit_transform(en_data).toarray()

In [ ]:
pd.DataFrame(ar, columns=['Gender_Female', 'Gender_Male', 'Married_No', 'Married_Yes'])

     Gender_Female  Gender_Male  Married_No  Married_Yes
0              0.0          1.0         1.0          0.0
1              0.0          1.0         0.0          1.0
2              0.0          1.0         0.0          1.0
3              0.0          1.0         0.0          1.0
4              0.0          1.0         1.0          0.0
..             ...          ...         ...          ...
609            1.0          0.0         1.0          0.0
610            0.0          1.0         0.0          1.0
611            0.0          1.0         0.0          1.0
612            0.0          1.0         0.0          1.0
613            1.0          0.0         1.0          0.0

[614 rows x 4 columns]